// <auto-generated />
using System;
using Kobe.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kobe.Data.Migrations
{
    [DbContext(typeof(KobeContext))]
    partial class KobeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Kobe.Domain.Entities.KobeCountry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Capital")
                        .IsRequired()
                        .HasColumnName("Capital")
                        .HasColumnType("varchar(150)");

                    b.Property<Guid?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<Guid>("KeyId");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("KobeCountry");
                });

            modelBuilder.Entity("Kobe.Domain.Entities.KobeUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("Email")
                        .HasColumnType("varchar(150)");

                    b.Property<byte[]>("HashedPassword")
                        .IsRequired()
                        .HasColumnName("HashedPassword")
                        .HasColumnType("binary(128)");

                    b.Property<bool>("IsDeactivated")
                        .HasColumnName("IsDeactivated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsLocked")
                        .HasColumnName("IsLocked")
                        .HasColumnType("bit");

                    b.Property<Guid>("KeyId");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnName("Salt")
                        .HasColumnType("binary(128)");

                    b.Property<string>("Token")
                        .HasColumnName("Token")
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime?>("TokenExpiryDate")
                        .HasColumnName("TokenExpiryDate")
                        .HasColumnType("DateTime");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnName("Username")
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("KobeUser");
                });
#pragma warning restore 612, 618
        }
    }
}
